// <auto-generated />
namespace MainApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedquestiontoCategoryId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedquestiontoCategoryId));
        
        string IMigrationMetadata.Id
        {
            get { return "201709270829526_added question to CategoryId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
