// <auto-generated />
namespace MainApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class disableautoincrementsecondattempt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(disableautoincrementsecondattempt));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281253078_disable auto increment(second attempt)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
