// <auto-generated />
namespace MainApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class fwefe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fwefe));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281432355_fwefe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
