// <auto-generated />
namespace MainApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class updatingcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041427061_updating context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
